Feature/rmteam 569 upgrade selenium in coypu and test new build with re motion
rubicon-oss/Fork.coypu pull request #2
Opened 2022-09-21 08:44 UTC by Frazerus

2022-09-21 11:24 UTC, a-ctor requested changes

2022-09-21 11:24 UTC, a-ctor commented on src/Coypu.AcceptanceTests/Examples/CustomBrowserSession.cs
> -        [TestCase("OS X 10.11", "safari", "11")]
I think we should undo the OS X change. The test always fails because we are no executing on OS X but we should do minimal changes to make it easier to integrate the fork in the future.

2022-09-21 11:24 UTC, a-ctor commented on src/Coypu/Coypu.csproj
> +    <Version>3.2.0.1</Version>
We should revert those as they are done as part of the actual release.

2022-09-21 13:24 UTC, Frazerus commented on src/Coypu.AcceptanceTests/Examples/CustomBrowserSession.cs
> -        [TestCase("OS X 10.11", "safari", "11")]
Im not sure thats how it works. 
Arent these remote tests, which get called externally?

We are also not running Windows 7, but the Win7 test is running fine.

2022-09-21 15:13 UTC, a-ctor commented on src/Coypu.AcceptanceTests/Examples/CustomBrowserSession.cs
> -        [TestCase("OS X 10.11", "safari", "11")]
What do you mean with remote tests?

The `TestCase` attribute supplies the parameters for the test which are used to determine the browser driver and the default options. The reason `Win7` works, is because the settings still work fine.

Safari only works with OS X so running the tests on a windows machine will always fail as Safari cannot be started. Since we are not using the Coypu tests at all, we can just keep the line in and have a failing test for something we don't need. This should make it easier to integrate the changes in the future if we wish to do that.

2022-09-22 06:45 UTC, Frazerus commented on src/Coypu.AcceptanceTests/Examples/CustomBrowserSession.cs
> -        [TestCase("OS X 10.11", "safari", "11")]
The problem here is that the test in question does not open the browser at all as it uses a remote driver. But lets talk about that in standup maybe.

I will leave the test in.

2022-09-22 07:50 UTC, a-ctor requested changes

2022-09-22 07:50 UTC, a-ctor commented on src/Coypu.AcceptanceTests/Examples/CustomBrowserSession.cs
>          public void CustomBrowserWithCustomRemoteDriver(string platformName,
We should revert the changes instead of moving the OS X entry to the back

2022-09-22 07:50 UTC, a-ctor commented on src/Coypu.AcceptanceTests/Examples/CustomBrowserSession.cs
> +
revert

2022-09-22 10:34 UTC, a-ctor approved these changes

2022-09-22 11:03 UTC, merged